"""Prompt templates for all LLM pipeline steps.

Design principle: each prompt describes ONLY the task at hand.
No prompt mentions pipeline stages, step numbers, "prior outputs", or
any other pipeline-internal concepts. Every prompt stands alone.

Naming convention:
P2_SYSTEM / P2_USER — Pre-processing: File Role Resolver
STEP1_SYSTEM / STEP1_USER — Structure Extraction
STEP2A_SYSTEM / STEP2A_USER — Normative Clause Extraction + Scoring
STEP3_SYSTEM / STEP3_USER — Interface Inference
STEP4_SYSTEM / STEP4_USER — SPL Emission

USER templates contain {{placeholder}} slots filled at runtime via the
render_* helpers at the bottom of this module.
"""

from __future__ import annotations
from prompts.p2_system import v1 as p2_sys
from prompts.step1_system import v2 as s1_sys
from prompts.step3_system import s3_a_v1 as s3_a, s3_b_v3 as s3_b
from prompts.step4_system import (
    s4_a_v2 as s4_a,
    s4_b_v3 as s4_b,
    s4_c_v2 as s4_c,
    s4_d_v2 as s4_d,
    s4_e_v4 as s4_e,
    s4_f_v1 as s4_f,
)
from prompts.step4_e1_system import v1 as s4_e1
from prompts.step4_e2_system import v1 as s4_e2

# ─────────────────────────────────────────────────────────────────────────────
# P2 — File Role Resolver
# ─────────────────────────────────────────────────────────────────────────────

P2_SYSTEM = p2_sys

P2_USER = """\
## SKILL.md reference sentences
Lines from SKILL.md that mention other files, with ±1 line of context.
Use these to judge how critically each file is referenced.

{{skill_md_references}}

## File inventory
Each entry: path [kind, size_bytes] followed by its first lines.

{{nodes_summary}}

## Reference edges
Which files each document mentions (doc → list of referenced files):

{{edges_json}}
"""

# ─────────────────────────────────────────────────────────────────────────────
# Step 1 — Structure Extraction
# ─────────────────────────────────────────────────────────────────────────────

STEP1_SYSTEM = s1_sys

STEP1_USER = """\
## Document package

{{merged_doc_text}}
"""

# ─────────────────────────────────────────────────────────────────────────────
# Step 3A — Entity Extraction
# Input: ARTIFACTS section + EXAMPLES section
# Output: {"entities": [...]}
# ─────────────────────────────────────────────────────────────────────────────

STEP3A_SYSTEM = s3_a

STEP3A_USER = """\
## Artifacts and data structures (primary entity source)

{{artifacts_section}}

## Workflow procedure (scan for additional entities produced or consumed by steps)

{{workflow_section}}

## Examples (use for schema_notes enrichment with concrete field names and types)

{{examples_section}}
"""

# ─────────────────────────────────────────────────────────────────────────────
# Step 3B — Workflow Analysis
# Input: WORKFLOW + TOOLS + EVIDENCE sections
# + NON_COMPILABLE clauses (JSON)
# + entity_ids list (constraint from Step 3A)
# Output: {workflow_steps, alternative_flows, exception_flows,
# interaction_requirements, needs_review_items}
# ─────────────────────────────────────────────────────────────────────────────

STEP3B_SYSTEM = s3_b

STEP3B_USER = """## Available entity_ids (from prior entity extraction)
Use ONLY these identifiers in prerequisites and produces.
Do NOT invent new entity_ids.

{{entity_ids_json}}

## A. Workflow procedure (ordered steps and branching logic)

{{workflow_section}}

## B. Tools, scripts, and capabilities mentioned

{{tools_section}}

## C. Evidence and validation requirements
Steps derived from these become is_validation_gate=true in workflow_steps.
If the source describes what to do when a step fails, also produce an
exception_flow for it.

{{evidence_section}}
"""

# ─────────────────────────────────────────────────────────────────────────────
# ─────────────────────────────────────────────────────────────────────────────
# Step 4 — SPL Emission (per-block prompts)
#
# Each SPL block is generated by a dedicated prompt pair. The LLM only sees
# the grammar for the block it is writing and the data that feeds exactly that
# block. Cross-block name consistency is enforced via a symbol table that is
# extracted after Round 1 and injected into the Round 2 (WORKER) prompt.
#
# Generation order
# ────────────────
# Round 1 (independent, can run in parallel):
# 4a PERSONA / AUDIENCE / CONCEPTS ← intent + notes text
# 4b CONSTRAINTS ← HARD + SOFT clauses
# 4c VARIABLES + FILES ← InterfaceSpec entities
# 4d APIS + GUARDRAIL ← EXPLICIT EXEC/NETWORK capabilities
#
# Round 2 (depends on Round 1 symbol table):
# 4e WORKER ← workflow steps + MEDIUM + NON clauses
# + symbol table from Round 1
#
# Shared annotation convention (referenced in every block prompt):
# # SOURCE_REF: <file>:<clause_id>
# # CONFIDENCE: <float 0.0-1.0>
# # NEEDS_REVIEW: true | false
# # ASSUMED: <reason> (when provenance != EXPLICIT)
# # LOW_CONFIDENCE: <reason> (when provenance == LOW_CONFIDENCE)
# # RISK_OVERRIDE: R=3 (when risk forced SOFT → MEDIUM)
# ─────────────────────────────────────────────────────────────────────────────

# ── 4a: PERSONA / AUDIENCE / CONCEPTS ────────────────────────────────────────

S4A_SYSTEM = s4_a

S4A_USER = """\
## INTENT section
Verbatim items from the document's purpose and scope description.
Use these to derive PERSONA (ROLE, DOMAIN, EXPERTISE) and AUDIENCE (if a user
group is explicitly named).

{{intent_text}}

## NOTES section
Verbatim items from background remarks, caveats, and rationale.
Scan for explicit term definitions to populate CONCEPTS.

{{notes_text}}
"""

# ── 4b: CONSTRAINTS ───────────────────────────────────────────────────────────

S4B_SYSTEM = s4_b

S4B_USER = """\
## Normative requirements from the CONSTRAINTS section

{{constraints_text}}

## Declared symbols (from DEFINE_VARIABLES, DEFINE_FILES, DEFINE_APIS)
When constraint description text refers to a declared variable, file, or
API by name, you may emit a <REF> reference.
Only reference names that appear in this list.

{{symbol_table}}
"""

# ── 4c: VARIABLES + FILES ─────────────────────────────────────────────────────

S4C_SYSTEM = s4_c

S4C_USER = """\
## A. StructuredSpec entities
Each entry has: entity_id, kind, type_name, schema_notes, is_file, file_path, provenance.

{{entities_json}}

## B. P1 omit-files (data/document/image/audio, read_priority=3)
These are package files not needed for normalization but potentially used at runtime.
Each entry has: path (relative), kind (data|document|image|audio), size_bytes.

{{omit_files_json}}
"""

# ── 4d: APIS + GUARDRAIL ──────────────────────────────────────────────────────

S4D_SYSTEM = s4_d

S4D_USER = """\
Generate DEFINE_APIS block for these tool specifications:

## Tools (SCRIPT, CODE_SNIPPET, NETWORK_API)

{{tools_json}}

For each tool, generate one API_DECLARATION following the rules in the system prompt.
"""

# ─────────────────────────────────────────────────────────────────────────────
# S4E — WORKER (updated)
#
# Key changes from prior version:
# - ALL workflow steps go in MAIN_FLOW (no NETWORK or validation-gate filtering)
# - ALTERNATIVE_FLOW driven by AlternativeFlowSpec (from Step 3B), not MEDIUM clauses
# - EXCEPTION_FLOW driven by ExceptionFlowSpec (from Step 3B), not auto-generated
# - [THROW] removed (not in grammar)
# - [INVOKE GuardrailName] removed (DEFINE_GUARDRAIL removed from grammar)
# - [EXAMPLES] block removed (generated separately by S4F)
# ─────────────────────────────────────────────────────────────────────────────

S4E_SYSTEM = s4_e

S4E_USER = """\
## A. Workflow steps (ALL steps — include NETWORK, USER_INPUT and validation-gate steps in MAIN_FLOW)
Each step has an action_type field: EXTERNAL_API | EXEC_SCRIPT | LOCAL_CODE_SNIPPET | LLM_TASK | FILE_READ | FILE_WRITE | USER_INTERACTION.

{{workflow_steps_json}}

## B. Available APIs (CRITICAL: Use these EXACT PascalCase names in [CALL ...] commands)
The following APIs were defined in the DEFINE_APIS block. You MUST use these EXACT PascalCase names
when generating [CALL ApiName ...] commands. Do NOT convert to snake_case or any other format.

{{apis_spl}}

## C. Tool information (for reference only - original tool specifications)
{{tools_json}}

## D. Original workflow prose (for branching logic and step ordering)

{{workflow_prose}}

## E. Alternative flows (for [ALTERNATIVE_FLOW: condition] blocks)
Each entry has: flow_id, condition (free text), description, steps (list of FlowStep objects).
Generate one ALTERNATIVE_FLOW block per entry. If empty, omit all ALTERNATIVE_FLOW blocks.

{{alternative_flows_json}}

## F. Exception flows (for [EXCEPTION_FLOW: condition] LOG blocks)
Each entry has: flow_id, condition (free text), log_ref (may be empty), steps (list of FlowStep objects).
Generate one EXCEPTION_FLOW block per entry. If empty, omit all EXCEPTION_FLOW blocks.

{{exception_flows_json}}
"""

# ─────────────────────────────────────────────────────────────────────────────
# S4E.1 — Block Nesting Detection
# Detects illegal BLOCK-inside-BLOCK patterns.
# ─────────────────────────────────────────────────────────────────────────────

S4E1_SYSTEM = s4_e1

S4E1_USER = """\
## WORKER SPL to analyze

{{worker_spl}}

Analyze this SPL [DEFINE_WORKER:] block and identify any nested BLOCK structures.
Respond with JSON only as specified in your instructions.
"""

# ─────────────────────────────────────────────────────────────────────────────
# S4E.2 — Block Nesting Fix
# Fixes illegal nested BLOCK structures by flattening.
# ─────────────────────────────────────────────────────────────────────────────

S4E2_SYSTEM = s4_e2

S4E2_USER = """\
## A. WORKER SPL with illegal nesting

{{worker_spl}}

## B. Detected violations

{{violations_json}}
"""


def render_s4e1_user(worker_spl: str) -> str:
    return S4E1_USER.replace("{{worker_spl}}", worker_spl)


def render_s4e2_user(worker_spl: str, violations_json: str) -> str:
    return (
        S4E2_USER
        .replace("{{worker_spl}}", worker_spl)
        .replace("{{violations_json}}", violations_json)
    )

# ─────────────────────────────────────────────────────────────────────────────
# S4F — EXAMPLES (new)
#
# Round 3: runs after S4E. Receives the fully generated WORKER SPL text
# and the original EXAMPLES section from the SectionBundle.
# Produces the [EXAMPLES] block to be inserted before [END_WORKER].
# ─────────────────────────────────────────────────────────────────────────────

S4F_SYSTEM = s4_f

S4F_USER = """\
## A. Generated WORKER SPL

{{worker_spl}}

## B. Original examples from skill documentation

{{examples_text}}
"""

# ─────────────────────────────────────────────────────────────────────────────
# Render helpers
# ─────────────────────────────────────────────────────────────────────────────

def render_p2_user(
    skill_md_references: str,
    nodes_summary: str,
    edges_json: str,
) -> str:
    return (P2_USER
    .replace("{{skill_md_references}}", skill_md_references)
    .replace("{{nodes_summary}}", nodes_summary)
    .replace("{{edges_json}}", edges_json))


def render_step1_user(merged_doc_text: str) -> str:
    return STEP1_USER.replace("{{merged_doc_text}}", merged_doc_text)


def render_step3a_user(
    artifacts_section: str,
    workflow_section: str,
    examples_section: str,
) -> str:
    return (
        STEP3A_USER
        .replace("{{artifacts_section}}", artifacts_section)
        .replace("{{workflow_section}}", workflow_section)
        .replace("{{examples_section}}", examples_section)
    )


def render_step3b_user(
    entity_ids_json: str,
    workflow_section: str,
    tools_section: str,
    evidence_section: str,
    available_tools: str = "[]",
) -> str:
    return (
        STEP3B_USER
        .replace("{{entity_ids_json}}", entity_ids_json)
        .replace("{{workflow_section}}", workflow_section)
        .replace("{{tools_section}}", tools_section)
        .replace("{{evidence_section}}", evidence_section)
        .replace("{{available_tools}}", available_tools)
    )


def render_s4a_user(intent_text: str, notes_text: str, symbol_table: str = "") -> str:
    return (
        S4A_USER
        .replace("{{intent_text}}", intent_text)
        .replace("{{notes_text}}", notes_text)
        .replace("{{symbol_table}}", symbol_table or "(none)")
    )


def render_s4b_user(constraints_text: str, symbol_table: str = "") -> str:
    return (
        S4B_USER
        .replace("{{constraints_text}}", constraints_text)
        .replace("{{symbol_table}}", symbol_table or "(none)")
    )


def render_s4c_user(entities_text: str, omit_files_text: str) -> str:
    return (S4C_USER
        .replace("{{entities_json}}", entities_text)
        .replace("{{omit_files_json}}", omit_files_text))


def render_s4d_user(tools_json: str) -> str:
    return S4D_USER.replace("{{tools_json}}", tools_json)


def render_s4e_user(
    workflow_steps_json: str,
    workflow_prose: str,
    alternative_flows_json: str,
    exception_flows_json: str,
    symbol_table: str,
    apis_spl: str = "",
    tools_json: str = "",
) -> tuple[str, str]:
    system = S4E_SYSTEM.replace("{{symbol_table}}", symbol_table)
    user = (
        S4E_USER
        .replace("{{workflow_steps_json}}", workflow_steps_json)
        .replace("{{workflow_prose}}", workflow_prose)
        .replace("{{apis_spl}}", apis_spl or "(no APIs declared)")
        .replace("{{alternative_flows_json}}", alternative_flows_json)
        .replace("{{exception_flows_json}}", exception_flows_json)
        .replace("{{tools_json}}", tools_json or "[]")
    )
    return system, user


def render_s4f_user(
    worker_spl: str,
    examples_text: str,
) -> str:
    return (
        S4F_USER
        .replace("{{worker_spl}}", worker_spl)
        .replace("{{examples_text}}", examples_text)
    )
