"""SPL assembly and formatting for Step 4."""
from __future__ import annotations

import logging

from pipeline.spl_formatter import format_spl_indentation
from pipeline.llm_steps.step4_spl_emission.utils import _strip_fences, _to_pascal_case

logger = logging.getLogger(__name__)


def _assemble_spl(
    skill_id: str,
    define_agent_header: str,
    block_4a: str,
    block_4b: str,
    block_4c: str,
    block_4d: str,
    block_4e: str,
    block_4f: str,
    types_spl: str = "",
) -> str:
    """Concatenate all blocks in canonical SPL order, wrapping with DEFINE_AGENT.

    Final structure:
    [DEFINE_AGENT: AGENT_NAME "description"]
    [DEFINE_TYPES:] (from types_spl, if provided)
    # SPL_PROMPT content (blocks 4a-4f)
    [END_AGENT]

    block_4f ([EXAMPLES] block) is inserted INSIDE the WORKER, before [END_WORKER].
    If [END_WORKER] is not found, 4f is appended separately.

    Args:
        types_spl: Optional [DEFINE_TYPES:] block from Step 3-T
    """
    # Insert S4F [EXAMPLES] block into the WORKER before [END_WORKER]
    worker_block = _strip_fences(block_4e.strip())
    if block_4f:
        examples_block = _strip_fences(block_4f.strip())
        if "[END_WORKER]" in worker_block:
            worker_block = worker_block.replace(
                "[END_WORKER]", examples_block + "\n[END_WORKER]", 1
            )
        else:
            worker_block = worker_block + "\n\n" + examples_block

    # Assemble SPL_PROMPT content (everything inside DEFINE_AGENT)
    spl_prompt_blocks = []
    for raw_block in (block_4a, block_4b, block_4c, block_4d):
        cleaned = _strip_fences(raw_block.strip())
        if cleaned:
            spl_prompt_blocks.append(cleaned)
    if worker_block:
        spl_prompt_blocks.append(worker_block)

    spl_prompt_content = "\n\n".join(spl_prompt_blocks)

    # Wrap with DEFINE_AGENT header and footer
    header = f"# SPL specification - {skill_id}\n# Generated by skill-to-cnlp pipeline\n\n"

    # Use the generated DEFINE_AGENT header (or create a default one)
    if define_agent_header and define_agent_header.strip():
        define_agent_line = _strip_fences(define_agent_header.strip())
    else:
        # Fallback: generate a simple DEFINE_AGENT header
        agent_name = _to_pascal_case(skill_id)
        define_agent_line = f"[DEFINE_AGENT: {agent_name}]"

    # Include types_spl if provided (from Step 3-T)
    types_block = _strip_fences(types_spl.strip()) if types_spl else ""

    # Assemble final SPL with proper ordering
    # Order: DEFINE_AGENT -> TYPES -> 4a-4f -> END_AGENT
    spl_blocks = [define_agent_line]
    if types_block:
        spl_blocks.append(types_block)
    spl_blocks.append(spl_prompt_content)

    final_spl = header + "\n\n".join(spl_blocks) + "\n\n[END_AGENT]"

    # Format SPL indentation, ensure using standard 4-space indentation
    final_spl = format_spl_indentation(final_spl)

    return final_spl