"""SPL assembly and formatting for Step 4."""
from __future__ import annotations

import logging

from pipeline.spl_formatter import format_spl_indentation
from pipeline.llm_steps.step4_spl_emission.utils import _strip_fences, _to_pascal_case

logger = logging.getLogger(__name__)


def _assemble_spl(
    skill_id: str,
    define_agent_header: str,
    block_4a: str,
    block_4b: str,
    block_4c: str,
    block_4d: str,
    block_4e: str,
    block_4f: str,
) -> str:
    """Concatenate all blocks in canonical SPL order, wrapping with DEFINE_AGENT.

    Final structure:
        [DEFINE_AGENT: AGENT_NAME "description"]
        # SPL_PROMPT content (blocks 4a-4f)
        [END_AGENT]

    block_4f ([EXAMPLES] block) is inserted INSIDE the WORKER, before [END_WORKER].
    If [END_WORKER] is not found, 4f is appended separately.
    """
    # Insert S4F [EXAMPLES] block into the WORKER before [END_WORKER]
    worker_block = _strip_fences(block_4e.strip())
    if block_4f:
        examples_block = _strip_fences(block_4f.strip())
        if "[END_WORKER]" in worker_block:
            worker_block = worker_block.replace(
                "[END_WORKER]", examples_block + "\n[END_WORKER]", 1
            )
        else:
            worker_block = worker_block + "\n\n" + examples_block

    # Assemble SPL_PROMPT content (everything inside DEFINE_AGENT)
    spl_prompt_blocks = []
    for raw_block in (block_4a, block_4b, block_4c, block_4d):
        cleaned = _strip_fences(raw_block.strip())
        if cleaned:
            spl_prompt_blocks.append(cleaned)
    if worker_block:
        spl_prompt_blocks.append(worker_block)

    spl_prompt_content = "\n\n".join(spl_prompt_blocks)

    # Wrap with DEFINE_AGENT header and footer
    header = f"# SPL specification - {skill_id}\n# Generated by skill-to-cnlp pipeline\n\n"

    # Use the generated DEFINE_AGENT header (or create a default one)
    if define_agent_header and define_agent_header.strip():
        define_agent_line = _strip_fences(define_agent_header.strip())
    else:
        # Fallback: generate a simple DEFINE_AGENT header
        agent_name = _to_pascal_case(skill_id)
        define_agent_line = f"[DEFINE_AGENT: {agent_name}]"

    final_spl = header + define_agent_line + "\n\n" + spl_prompt_content + "\n\n[END_AGENT]"

    # Format SPL indentation, ensure using standard 4-space indentation
    final_spl = format_spl_indentation(final_spl)

    return final_spl